#sudo: required
language: generic
services:
    - docker

before_install:
    - docker build -t sathish1983/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true sathish1983/docker-react npm run test
    